name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mostrando variables de entorno
      run: |
        printenv
    - name: Run Tests
      env:
        SIGNING_KEY_NAME_FILE: ${{ secrets.SIGNING_KEY_NAME_FILE }}
        VERIFYING_KEY_NAME_FILE: ${{ secrets.VERIFYING_KEY_NAME_FILE }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_RECEIVER_TEST: ${{ secrets.EMAIL_RECEIVER_TEST }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        DB_ENGINE: ${{ env.DB_ENGINE }}
        DB_NAME: ${{ env.DB_NAME }}
        EMAIL_HOST: ${{ env.EMAIL_HOST }}
        EMAIL_PORT: ${{ env.EMAIL_PORT }}
        EMAIL_USE_SSL: ${{ env.EMAIL_USE_SSL }}

      run: |
        python manage.py test
